# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Max: 88

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
   - constants
   - module_inclusion
   - association
   - public_attribute_macros
   - public_delegate
   - macros
   - public_class_methods
   - initializer
   - public_methods
   - protected_attribute_macros
   - protected_methods
   - private_attribute_macros
   - private_delegate
   - private_methods
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: diff_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: diff_comma
